package com.dxm.anymock.common.base.enums;

public enum SuccessMsg {
    SPACE_INSERT_SUCCESS,
    SPACE_UPDATE_SUCCESS,
    SPACE_DELETE_SUCCESS,
    HTTP_INTERFACE_INSERT_SUCCESS,
    HTTP_INTERFACE_UPDATE_SUCCESS,
    HTTP_INTERFACE_DELETE_SUCCESS,
    HTTP_INTERFACE_START_SUCCESS,
    HTTP_INTERFACE_SHUTDOWN_SUCCESS
}
